# src/Acme/HelloBundle/Resources/config/routing.yml
acme_hello_homepage:
    path:     /
    defaults: { _controller: AcmeHelloBundle:Default:index }

hello:
    path:     /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Hello:index }

nombre_apellidos:
    path:     /hello/{name}/{apellidos}
    defaults: { _controller: AcmeHelloBundle:Hello:nameapellidos }
